### ISSUE TITLE
Run as administrator?

### ISSUE THREAD

**Issue by scaglar78** [Barben360/VPNUnlimited2Syno#1]
Hi
What do you mean by "Run "./Setup" as an administrator ". Can you elaborate?
I have connected to the NAS via SSH using a user in administrators group.
However, I still get following error when I execute the script as _VPNUnlimited2Syno-master$ python3 Setup_

#############################################
#############################################
Creating backup of previous ovpn configuration...
Reading previous ovpn configuration...
Reading and extracting VPN Unlimited configurations...
Setting up VPN configurations...
Copying to Synology VPN folder...
Traceback (most recent call last):
  File "Setup", line 174, in <module>
    shutil.copyfile(os.path.join("./output", filename), os.path.join(syno_folder,filename))
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/syno/etc/synovpnclient/openvpn/ovpnclient.conf'

Hope you can help

Thanks

**Comment by Barben360** [comment]
You just need to have the admin rights to modify the file "/usr/syno/etc/synovpnclient/openvpn/ovpnclient.conf".
Just type:
`sudo python3 Setup`
and enter your password.
That should do the job.
