### ISSUE TITLE
-sh: ./Setup: /usr/bin/python3: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by saibhargavk** [Barben360/VPNUnlimited2Syno#3]
Hey,

I am getting the below error when I try to run this script to add VPN Unlimited config on my Synology NAS. -sh: ./Setup: /usr/bin/python3: bad interpreter: No such file or directory

Please help.

Thanks.

**Comment by saibhargavk** [comment]
If this helps: I am doing ssh from a Mac terminal.

**Comment by Barben360** [comment]
Hello,
This means you have not installed python3 on your DiskStation. Go to package manager on the web interface, search "Python 3" and install it. Then everything should work as expected.

**Comment by ElFrancky** [comment]
EDIT : 
solved with this response : 
I got it to work with the following command:
/usr/bin/env python3 ./Setup

Not sure why the python 3 install screwed up the environmental variable but after running it my VPN connection worked just fine after selecting the correct file from the Synology Network panel.

----------------------------------------------------


Hi, I've the same issue. Python is well installed on my DS216+.
Can you help me 

error got : sudo: unable to execute ./Setup: No such file or directory
